#gitのアレを左端に表示するやつ
[[plugins]]
repo = 'airblade/vim-gitgutter'


[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#icon追加するやつ
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'catppuccin/nvim'

#もしかしていらない？
#[[plugins]]
#repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
    let g:neosnippet#snippets_directory = '$HOME/.config/nvim/snippets'
    let g:insert = 1
    let g:filetypes = 'snippet'
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-surround'

#TODO: 要設定
[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo =  'mbbill/undotree'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
    autocmd BufRead,BufNewFile *.md  set filetype=markdown
    nnoremap <silent> <C-p> :PrevimOpen<CR>
    let g:vim_markdown_folding_disabled=1
    let g:previm_enable_realtime = 1
'''
[[plugins]]
repo = 'nametake/vim-goiferr-snippets'

[[plugins]]
repo = 'glacambre/firenvim'
hook_post_update = '''
    call firenvim#install(0)
'''

[[plugins]]
repo = '907th/vim-auto-save'
on_event = 'InsertLeave'
hook_add = '''
  let g:auto_save = 1
  let g:auto_save_no_updatetime = 1
  let g:auto_save_in_insert_mode = 0
  let g:auto_save_silent = 1
'''

[[plugins]]
repo = 'lervag/vimtex'
hook_add = '''
let g:tex_flavor = 'xelatex'
let g:vimtex_compiler_method = 'tectonic'
'''
